-- Widget library
local wibox = require("wibox")
-- Custom library
local dwidget = require("dynamo.widget")

-- { Create powerline section with separator and fill color
-- @param number index Index of section, used for autogenerated color
-- @param string icon Icon path of section
-- @param string color_current Hexa or name color of this section
-- @param string color_next Hexa or name color of next section (left-to-right for index > 0, unless is right-to-left)
-- @return table Table with information of section
local function create(index, icon, color_current, color_next)
  local section = {}

  local separator_direction
  if index > 0 then
    section.separator = dwidget.separator("arrow", "right", "solid", color_current, color_next)
  else
    section.separator = dwidget.separator("arrow", "left", "solid", color_next, color_current)
  end
  section.icon = wibox.container.background(wibox.widget.imagebox(icon), color_current)
  section.text = wibox.widget.textbox()
  section.background = wibox.container.background(section.text, color_current)

  function section:buttons(_buttons)
    section.icon:buttons(_buttons)
    section.background:buttons(_buttons)
  end

  function section:connect_signal(signal, execute)
    section.icon:connect_signal(signal, execute)
    section.background:connect_signal(signal, execute)
  end

  return section
end
-- }

return setmetatable({}, { __call = function(_, ...) return create(...) end })
